default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  host:     localhost
  username: postgres
  password: postgres
  template: template0


development:
  <<: *default
  database: aureso_web_development

test:
  <<: *default
  database: aureso_web_test

production:
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>